apiVersion: v1
kind: Template
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: squid
    spec:
      dockerImageRepository: jameseckersall/squid
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      creationTimestamp: null
      generation: 4
      labels:
        app: squid
      name: squid
    spec:
      replicas: 1
      selector:
        app: squid
        deploymentconfig: squid
      strategy:
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: squid
            deploymentconfig: squid
        spec:
          containers:
          - image: jameseckersall/squid
            imagePullPolicy: Always
            readinessProbe:
              initialDelaySeconds: 5
              timeoutSeconds: 5
              exec:
                command:
                - squidclient -h localhost cache_object://localhost mgr:info
            livenessProbe:
              initialDelaySeconds: 5
              timeoutSeconds: 30
              exec:
                command:
                - squidclient -h localhost cache_object://localhost mgr:info
            name: squid
            ports:
            - containerPort: 3128
              protocol: TCP
            env:
            - name: SQUID_USERNAME
              value: ${SQUID_USERNAME}
            - name: SQUID_PASSWORD
              value: ${SQUID_PASSWORD}
            resources: {}
            terminationMessagePath: /dev/termination-log
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          securityContext: {}
          terminationGracePeriodSeconds: 30
      triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
          - squid
          from:
            kind: ImageStreamTag
            name: squid:latest
            namespace: test
        type: ImageChange
  - apiVersion: v1
    kind: Route
    metadata:
      creationTimestamp: null
      labels:
        app: squid
      name: squid
    spec:
      host: ${SQUID_ROUTE}
      port:
        targetPort: 3128-tcp
      to:
        kind: Service
        name: squid
        weight: 100
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        app: squid
      name: squid
    spec:
      ports:
      - name: 3128-tcp
        port: 3128
        protocol: TCP
        targetPort: 3128
      selector:
        app: squid
        deploymentconfig: squid
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}
parameters:
- name: SQUID_ROUTE
  required: false
- name: SQUID_USERNAME
  value: squid
  required: true
- name: SQUID_PASSWORD
  value: squid
  required: true
  generate: expression
  from: "[a-zA-Z0-9]{20}"
